name: iris_social_network
description: Iris Social Network

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.1+13

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #flare_flutter: ^1.5.0

  flare_flutter: ^1.5.4

  flare_dart: ^1.4.0

  #camera: ^0.5.2+2
  #camera: ^0.5.6+3
  camera: ^0.5.7+2

  # The following adds firebase dependencies
  #firebase_core: ^0.4.0
  #firebase_core: ^0.4.0+9
  firebase_core: ^0.4.3+1
  #firebase_auth: ^0.11.1+6
  #firebase_auth: ^0.14.0+5
  firebase_auth: ^0.15.3
  #firebase_analytics: ^5.0.2
  firebase_analytics: ^5.0.9
  #firebase_analytics: ^5.0.1
  #firebase_messaging: ^3.0.0
  #firebase_messaging: ^5.1.4
  #firebase_messaging: ^5.1.5
  firebase_messaging: ^5.1.6
  #firebase_storage: ^3.0.1
  #firebase_storage: ^3.0.6
  firebase_storage: ^3.1.0
  #firebase_database: ^3.0.5
  #firebase_database: ^3.0.7
  firebase_database: ^3.1.1
  #cloud_firestore: ^0.12.5
  #cloud_firestore: ^0.12.9+4
  cloud_firestore: ^0.13.0+1
  #google_sign_in: ^4.0.2
  google_sign_in: ^4.1.1
  flutter_facebook_login: ^2.0.1
  #firebase_dynamic_links: ^0.5.0+1
  firebase_dynamic_links: ^0.5.0+9
  #firebase_remote_config: ^0.2.0+7
  firebase_remote_config: ^0.3.0+1

  http: ^0.12.0+1
  dio: ^2.1.13

  #package_info: ^0.4.0+10
  package_info: ^0.4.0+13
  #country_pickers: ^1.0.1
  country_pickers: ^1.1.0
  #rxdart: ^0.22.0
  rxdart: ^0.22.2
  #scoped_model: ^1.0.1
  #intl: ^0.15.7
  intl: ^0.16.0
  #connectivity: ^0.4.2
  #connectivity: ^0.4.4
  connectivity: ^0.4.6+1
  data_connection_checker: ^0.3.4
  after_layout: ^1.0.7+2

  #image: ^2.0.7
  image: ^2.1.4

  #flip_card: ^0.2.1
  #pin_code_text_field: ^1.1.3
  #pin_code_text_field: ^1.3.7
  pin_code_text_field: ^1.4.0
  #fluttertoast: 2.2.4
  flutter_spinkit: ^3.1.0
  #intro_slider: ^1.1.4
  #image_picker: ^0.6.0+17
  image_picker: ^0.6.1+4
  file_picker: ^1.3.8
  #page_transition: ^1.0.8
  font_awesome_flutter: ^8.4.0
  #fancy_bottom_navigation: ^0.3.2
  painter: ^0.3.1
  flutter_colorpicker: ^0.2.1
  random_pk: ^0.0.3
  #wave: ^0.0.8
  backdrop: ^0.1.8
  photo_view: ^0.4.2
  flutter_custom_clippers: ^0.1.6
  flutter_slidable: ^0.4.9
  flutter_staggered_grid_view: ^0.2.7
  page_indicator: ^0.2.0
  flutter_auth_buttons: ^0.5.0
  #liquid_pull_to_refresh: ^1.1.1
  marquee: ^1.2.0
  avatar_glow: ^0.2.0
  percent_indicator: ^2.1.1
  flutter_rating_bar: ^2.0.0
  emoji_picker: ^0.0.2
  page_view_indicator: ^2.0.2
  peek_and_pop: ^1.0.2
  dots_indicator: ^1.0.0
  palette_generator: ^0.2.0
  flutter_signin_button: ^0.5.2
  liquid_progress_indicator: ^0.3.2
  simple_animations: ^1.3.4

  animated_background: ^1.0.5
  animated_text_kit: ^1.3.0
  circle_wheel_scroll: ^0.0.1+1
  flutter_swiper: ^1.1.6
  universal_widget: ^1.2.5
  #extended_image: ^0.5.3
  extended_image: ^0.6.8
  gradient_widgets: ^0.5.0
  #animator: ^0.1.4
  animator: ^1.0.0
  time_ago_provider: ^1.0.3
  flutter_widgets: ^0.1.5
  #avataaar_image: ^1.0.6
  avataaar_image: ^1.0.7
  confetti: ^0.1.1
  bubble: ^1.1.9+1
  sticky_headers: ^0.1.8
  curved_navigation_bar: ^0.3.1
  flutter_material_color_picker: ^1.0.5


  #shared_preferences: ^0.5.0
  #shared_preferences: ^0.4.0
  #shared_preferences: ^0.5.1+1
  shared_preferences: ^0.5.3+4
  #shared_preferences: ^0.4.3
  #path_provider: ^0.5.0+1
  path_provider: ^1.1.0
  #path_provider: ^0.4.1
  #flutter_cache_manager: ^0.2.0+1
  #flutter_cache_manager: ^0.3.0
  flutter_cache_manager: ^1.0.0
  #cached_network_image: ^1.0.0
  cached_network_image: ^1.1.3
  #cached_network_image: ^2.0.0-rc
  permission_handler: ^3.1.0
  contacts_service: ^0.2.3
  #chewie: ^0.9.6
  chewie: ^0.9.8+1
  gallery_saver: ^1.0.6

  #video_player: ^0.10.1+3
  #video_player: ^0.10.2
  #video_player: ^0.10.2+3
  video_player: ^0.10.5+1
  #flutter_ffmpeg: ^0.1.1
  flutter_video_compress: ^0.3.7+8
  #speech_recognition: ^0.3.0+1
  flutter_image_compress: ^0.6.3
  audioplayers: ^0.13.1
  #audio_recorder: ^1.0.1
  soundpool: ^0.5.3
  share: ^0.6.2+1
  flutter_sound: ^1.4.3
  #url_launcher: ^5.2.1
  url_launcher: ^5.4.1
  true_time: ^0.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/medias/images/default_profile_image.jpg
    - assets/medias/images/music_note_animation.gif
    - assets/medias/images/audios_background_image.jpg
    - assets/medias/images/audios_background_image_aurora.jpg
    - assets/medias/images/audios_background_image_orion_nebula.jpg
    - assets/medias/images/images_background_image.jpg
    - assets/medias/images/videos_background_image.jpg



    # friends feed background image
    - assets/medias/images/friends_feed_background_image_girls.jpg
    - assets/medias/images/friends_feed_background_image_friend_logo.jpg
    - assets/medias/images/friends_feed_background_image_love.jpg
    - assets/medias/images/friends_feed_background_image_people.jpg
    - assets/medias/images/friends_feed_background_image_sunset.jpg

    # video feed slide show images
    - assets/medias/images/video_feeds_slideshow_images/all_talents.jpg
    - assets/medias/images/video_feeds_slideshow_images/singing.jpg
    - assets/medias/images/video_feeds_slideshow_images/dancing.jpg
    - assets/medias/images/video_feeds_slideshow_images/sports.jpg
    - assets/medias/images/video_feeds_slideshow_images/magic.jpg
    - assets/medias/images/video_feeds_slideshow_images/modeling.jpg
    - assets/medias/images/video_feeds_slideshow_images/fashion.jpg
    - assets/medias/images/video_feeds_slideshow_images/comedy.jpg


    # talent images
    - assets/medias/images/talent_images/ballerina.png
    - assets/medias/images/talent_images/basketball.png
    - assets/medias/images/talent_images/break-dance.png
    - assets/medias/images/talent_images/breakdance1.png
    - assets/medias/images/talent_images/breakdance2.png
    - assets/medias/images/talent_images/carefree_group.png
    - assets/medias/images/talent_images/carefree_solo.png
    - assets/medias/images/talent_images/flip_dance.png
    - assets/medias/images/talent_images/football.png
    - assets/medias/images/talent_images/girl_dancing.png
    - assets/medias/images/talent_images/girl_singing.png
    - assets/medias/images/talent_images/girl_jumping.png
    - assets/medias/images/talent_images/skateboard.png
    - assets/medias/images/talent_images/kids.png
    - assets/medias/images/talent_images/singer.png
    - assets/medias/images/talent_images/soccer.png
    - assets/medias/images/talent_images/karate.png

    # Profile Sound Tracks
    - assets/medias/audios/profile_sound_tracks/bensound-acousticbreeze.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-anewbeginning.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-creativeminds.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-cute.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-goinghigher.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-happyrock.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-hey.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-jazzyfrenchy.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-littleidea.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-memories.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-summer.mp3
    - assets/medias/audios/profile_sound_tracks/bensound-ukulele.mp3



    # flare assets
    - assets/flare/like.flr
    - assets/flare/teddy.flr
    - assets/flare/success.flr
    - assets/flare/shooting_stars.flr



  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
