

final List countriesList = [

  {"isoCode": "AO", "phoneCode": "244", "name": "Angola"},
  {"isoCode": "AR", "phoneCode": "54", "name": "Argentina"},
  {"isoCode": "AS", "phoneCode": "1-684", "name": "American Samoa"},
  {"isoCode": "AT", "phoneCode": "43", "name": "Austria"},
  {"isoCode": "AU", "phoneCode": "61", "name": "Australia"},

  {"isoCode": "BE", "phoneCode": "32", "name": "Belgium"},
  {"isoCode": "BF", "phoneCode": "226", "name": "Burkina Faso"},
  {"isoCode": "BG", "phoneCode": "359", "name": "Bulgaria"},
  {"isoCode": "BI", "phoneCode": "257", "name": "Burundi"},
  {"isoCode": "BJ", "phoneCode": "229", "name": "Benin"},
  {"isoCode": "BR", "phoneCode": "55", "name": "Brazil"},
  {"isoCode": "BV", "phoneCode": "47", "name": "Bouvet Island"},
  {"isoCode": "BW", "phoneCode": "267", "name": "Botswana"},
  {"isoCode": "CA", "phoneCode": "1", "name": "Canada"},
  {
    "isoCode": "CD",
    "phoneCode": "243",
    "name": "Congo, the Democratic Republic of the"
  },
  {"isoCode": "CF", "phoneCode": "236", "name": "Central African Republic"},
  {"isoCode": "CG", "phoneCode": "242", "name": "Congo"},
  {"isoCode": "CH", "phoneCode": "41", "name": "Switzerland"},
  {"isoCode": "CI", "phoneCode": "225", "name": "C\u00f4te d'Ivoire"},
  {"isoCode": "CL", "phoneCode": "56", "name": "Chile"},
  {"isoCode": "CM", "phoneCode": "237", "name": "Cameroon"},
  {"isoCode": "CN", "phoneCode": "86", "name": "China"},
  {"isoCode": "CO", "phoneCode": "57", "name": "Colombia"},
  {"isoCode": "CR", "phoneCode": "506", "name": "Costa Rica"},
  {"isoCode": "CU", "phoneCode": "53", "name": "Cuba"},
  {"isoCode": "CV", "phoneCode": "238", "name": "Cape Verde"},
  {"isoCode": "DE", "phoneCode": "49", "name": "Germany"},
  {"isoCode": "DJ", "phoneCode": "253", "name": "Djibouti"},
  {"isoCode": "DK", "phoneCode": "45", "name": "Denmark"},
  {"isoCode": "DZ", "phoneCode": "213", "name": "Algeria"},
  {"isoCode": "EG", "phoneCode": "20", "name": "Egypt"},
  {"isoCode": "EH", "phoneCode": "212", "name": "Western Sahara"},
  {"isoCode": "ES", "phoneCode": "34", "name": "Spain"},
  {"isoCode": "ET", "phoneCode": "251", "name": "Ethiopia"},
  {"isoCode": "FI", "phoneCode": "358", "name": "Finland"},
  {"isoCode": "FR", "phoneCode": "33", "name": "France"},
  {"isoCode": "GA", "phoneCode": "241", "name": "Gabon"},
  {"isoCode": "GB-ENG", "phoneCode": "44", "name": "England"},
  {"isoCode": "GB-NIR", "phoneCode": "44", "name": "Northern Ireland"},
  {"isoCode": "GB-SCT", "phoneCode": "44", "name": "Scotland"},
  {"isoCode": "GB-WLS", "phoneCode": "44", "name": "Wales"},
  {"isoCode": "GB", "phoneCode": "44", "name": "United Kingdom"},
  {"isoCode": "GD", "phoneCode": "1-473", "name": "Grenada"},
  {"isoCode": "GE", "phoneCode": "995", "name": "Georgia"},
  {"isoCode": "GH", "phoneCode": "233", "name": "Ghana"},
  {"isoCode": "GL", "phoneCode": "299", "name": "Greenland"},
  {"isoCode": "GM", "phoneCode": "220", "name": "Gambia"},
  {"isoCode": "GN", "phoneCode": "224", "name": "Guinea"},
  {"isoCode": "GQ", "phoneCode": "240", "name": "Equatorial Guinea"},
  {"isoCode": "GR", "phoneCode": "30", "name": "Greece"},
  {
    "isoCode": "GS",
    "phoneCode": "500",
    "name": "South Georgia and the South Sandwich Islands"
  },
  {"isoCode": "GW", "phoneCode": "245", "name": "Guinea-Bissau"},
  {"isoCode": "HK", "phoneCode": "852", "name": "Hong Kong"},
  {"isoCode": "HN", "phoneCode": "504", "name": "Honduras"},
  {"isoCode": "HR", "phoneCode": "385", "name": "Croatia"},
  {"isoCode": "HU", "phoneCode": "36", "name": "Hungary"},
  {"isoCode": "IE", "phoneCode": "353", "name": "Ireland"},
  {"isoCode": "IN", "phoneCode": "91", "name": "India"},
  {
    "isoCode": "IO",
    "phoneCode": "246",
    "name": "British Indian Ocean Territory"
  },
  {"isoCode": "IR", "phoneCode": "98", "name": "Iran, Islamic Republic of"},
  {"isoCode": "IS", "phoneCode": "354", "name": "Iceland"},
  {"isoCode": "IT", "phoneCode": "39", "name": "Italy"},
  {"isoCode": "JP", "phoneCode": "81", "name": "Japan"},
  {"isoCode": "KE", "phoneCode": "254", "name": "Kenya"},
  {
    "isoCode": "KP",
    "phoneCode": "850",
    "name": "Korea, Democratic People's Republic of"
  },
  {"isoCode": "KR", "phoneCode": "82", "name": "Korea, Republic of"},
  {"isoCode": "KZ", "phoneCode": "7", "name": "Kazakhstan"},

  {"isoCode": "LK", "phoneCode": "94", "name": "Sri Lanka"},
  {"isoCode": "LR", "phoneCode": "231", "name": "Liberia"},
  {"isoCode": "LS", "phoneCode": "266", "name": "Lesotho"},
  {"isoCode": "LT", "phoneCode": "370", "name": "Lithuania"},
  {"isoCode": "LU", "phoneCode": "352", "name": "Luxembourg"},
  {"isoCode": "LY", "phoneCode": "218", "name": "Libya"},
  {"isoCode": "MA", "phoneCode": "212", "name": "Morocco"},
  {"isoCode": "MC", "phoneCode": "377", "name": "Monaco"},
  {"isoCode": "ML", "phoneCode": "223", "name": "Mali"},
  {"isoCode": "MW", "phoneCode": "265", "name": "Malawi"},
  {"isoCode": "MX", "phoneCode": "52", "name": "Mexico"},
  {"isoCode": "MY", "phoneCode": "60", "name": "Malaysia"},
  {"isoCode": "MZ", "phoneCode": "258", "name": "Mozambique"},
  {"isoCode": "NA", "phoneCode": "264", "name": "Namibia"},
  {"isoCode": "NE", "phoneCode": "227", "name": "Niger"},
  {"isoCode": "NG", "phoneCode": "234", "name": "Nigeria"},
  {"isoCode": "NL", "phoneCode": "31", "name": "Netherlands"},
  {"isoCode": "NO", "phoneCode": "47", "name": "Norway"},
  {"isoCode": "NZ", "phoneCode": "64", "name": "New Zealand"},
  {"isoCode": "PE", "phoneCode": "51", "name": "Peru"},
  {"isoCode": "PH", "phoneCode": "63", "name": "Philippines"},
  {"isoCode": "PK", "phoneCode": "92", "name": "Pakistan"},
  {"isoCode": "PL", "phoneCode": "48", "name": "Poland"},
  {"isoCode": "PT", "phoneCode": "351", "name": "Portugal"},
  {"isoCode": "PY", "phoneCode": "595", "name": "Paraguay"},
  {"isoCode": "QA", "phoneCode": "974", "name": "Qatar"},
  {"isoCode": "RE", "phoneCode": "262", "name": "Réunion"},
  {"isoCode": "RO", "phoneCode": "40", "name": "Romania"},
  {"isoCode": "RS", "phoneCode": "381", "name": "Serbia"},
  {"isoCode": "RU", "phoneCode": "7", "name": "Russian Federation"},
  {"isoCode": "RW", "phoneCode": "250", "name": "Rwanda"},
  {"isoCode": "SD", "phoneCode": "249", "name": "Sudan"},
  {"isoCode": "SE", "phoneCode": "46", "name": "Sweden"},
  {"isoCode": "SG", "phoneCode": "65", "name": "Singapore"},
  {"isoCode": "SI", "phoneCode": "386", "name": "Slovenia"},
  {
    "isoCode": "SJ",
    "phoneCode": "47",
    "name": "Svalbard and Jan Mayen Islands"
  },
  {"isoCode": "SK", "phoneCode": "421", "name": "Slovakia"},
  {"isoCode": "SL", "phoneCode": "232", "name": "Sierra Leone"},
  {"isoCode": "SM", "phoneCode": "378", "name": "San Marino"},
  {"isoCode": "SN", "phoneCode": "221", "name": "Senegal"},
  {"isoCode": "SO", "phoneCode": "252", "name": "Somalia"},
  {"isoCode": "SS", "phoneCode": "211", "name": "South Sudan"},
  {"isoCode": "SZ", "phoneCode": "268", "name": "Swaziland"},
  {"isoCode": "TD", "phoneCode": "235", "name": "Chad"},
  {"isoCode": "TF", "phoneCode": "262", "name": "French Southern Territories"},
  {"isoCode": "TG", "phoneCode": "228", "name": "Togo"},
  {"isoCode": "TH", "phoneCode": "66", "name": "Thailand"},
  {"isoCode": "TN", "phoneCode": "216", "name": "Tunisia"},
  {"isoCode": "TO", "phoneCode": "676", "name": "Tonga"},
  {"isoCode": "TR", "phoneCode": "90", "name": "Turkey"},
  {"isoCode": "TZ", "phoneCode": "255", "name": "Tanzania, United Republic of"},
  {"isoCode": "UA", "phoneCode": "380", "name": "Ukraine"},
  {"isoCode": "UG", "phoneCode": "256", "name": "Uganda"},
  {"isoCode": "UM", "phoneCode": "1", "name": "US Minor Outlying Islands"},
  {"isoCode": "US", "phoneCode": "1", "name": "United States"},
  {"isoCode": "UY", "phoneCode": "598", "name": "Uruguay"},

  {
    "isoCode": "VE",
    "phoneCode": "58",
    "name": "Venezuela, Bolivarian Republic of"
  },

  {"isoCode": "ZA", "phoneCode": "27", "name": "South Africa"},
  {"isoCode": "ZM", "phoneCode": "260", "name": "Zambia"},
  {"isoCode": "ZW", "phoneCode": "263", "name": "Zimbabwe"},
];
